version: '3.8'

services:
  sentiment-backend:
    image: amaronetto/sentiment-backend:final
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sentiment_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=hackathon
    depends_on:
      - db
      - sentiment-ai

  sentiment-frontend:
    image: amaronetto/sentiment-frontend:final
    ports:
      - "3000:80"

  sentiment-ai:
    image: amaronetto/sentiment-ai:final
    ports:
      - "5000:5000"

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=sentiment_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hackathon
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: